name: Deploy via SFTP
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          user: root
          pass: ${{ secrets.SFTP_PASS }}
          # lftp settings
          # onlyNewer: true
          settings: 'sftp:auto-confirm=yes'
          # Mirror command options
          localDir: '.'
          remoteDir: '/var/www/html/wp-content/themes/vj/'
          # reverse: false
          # ignoreFile: '.lftp_ignore'
          options: '--verbose'
